### ISSUE TITLE
Zoom Recipe

### ISSUE THREAD

**Issue by humm3r1** [AccessOwl/open_owl#1]
Hello,

I think I've gotten part of the recipe ready for Zoom support but just having a bit of difficulty finding the selector piece for the username and password prompts.

A fair warning I am not a developer so this is outside of my expertise area :) 

When you sign in on the login_url using a browser, it sends you to whichever zone, datacenter, cluster, etc. such as us06web.zoom.us, so not sure if I need more asterisks for the destination_url_pattern to match the length of this subdomain above.

Once signed in though, you can drop the subdomain and just use zoom.us to pull up the basic user list, and anyone with type = 1 in the result will have basic license, anyone with type = 2 is licensed with a meetings license.

Using the below recipe addition in testing, it times out, likely because it's not finding the correct selectors. I do have the same subdomain above in my destination_url_pattern when testing this out before trying wildcards (asterisks).

Here is the element for the username box on Zoom's login page:

`<input type="email" autocomplete="email" name="email" placeholder="" aria-required="true" aria-label="Email Address" id="email" maxlength="128" class="zm-input__inner">`

And here is my recipe addition so far:

zoom:
  login_url: https://zoom.us/signin#/login
  destination_url_pattern: https://**.zoom.us/profile
  username_selector: "data-testid=email"
  password_selector: "data-testid=password"
  actions:
    - name: download_users
      http_method: GET
      url: https://zoom.us/account/user/list_basic
      response_path: data
      pagination:
        strategy: url_in_body
        next_url_response_path: nextLink

**Comment by MMore** [comment]
Hey @humm3r1,
amazing how you played around with it! I checked Zoom and it seems there are some things that need to be developed and fixed so that it works completely out of the box. Until now I can give you this adjusted recipe:

```yaml
zoom:
  login_url: https://zoom.us/account/user#/
  destination_url_pattern: https://zoom.us/account/user#/
  username_selector: "internal:label=\"Email Address\"i"
  password_selector: "internal:label=\"Password\"i"
  actions:
    - name: download_users
      http_method: GET
      url: https://zoom.us/account/user/list_basic
      response_path: result.data
```

We figured the following limitations of this Zoom recipe:
- pagination is not working yet
- result columns might not be aligned for several users as it seems that Zoom just skips columns when there is no data in it

BTW: If you would still have issues logging in, you might need to disable the "One-Time Passcode Authentication" temporarily under https://zoom.us/account/setting/security so that the login is not blocked.
Under the `results` folder is a screenshot folder which is filled when the login is stuck. That might help for debugging purposes.
